export enum UserAction {
  SIGNUP = "SIGNUP",
  LOGIN_PER_DAY = "LOGIN_PER_DAY",
  BIRTHDAY = "BIRTHDAY",
  ASK_QUESTION = "ASK_QUESTION",
  ASK_POLL = "ASK_POLL",
  QUESTION_ASKER_LIKE = "QUESTION_ASKER_LIKE",
  POLL_ASKER_LIKE = "POLL_ASKER_LIKE",
  QUESTION_ASKER_LIKE_10 = "QUESTION_ASKER_LIKE_10",
  QUESTION_ASKER_LIKE_50 = "QUESTION_ASKER_LIKE_50",
  POLL_ASKER_LIKE_HIGH = "POLL_ASKER_LIKE_HIGH",
  COMMENT_ON_POST = "COMMENT_ON_POST",
  COMMENT_LIKED_10 = "COMMENT_LIKED_10",
  COMMENT_LIKED_50 = "COMMENT_LIKED_50",
  DELETE_QUESTION = "DELETE_QUESTION",
  DELETE_POLL = "DELETE_POLL",
  UPDATE_QUESTION = "UPDATE_QUESTION",
  DELETE_COMMENT = "DELETE_COMMENT",
  DELETE_REPLY = "DELETE_REPLY",
  SEND_PRIVATE_MESSAGE = "SEND_PRIVATE_MESSAGE",
  SPECIAL_DAY_LOGIN = "SPECIAL_DAY_LOGIN",
  VOTE_ON_POLL = "VOTE_ON_POLL",
  POST_HEART_RECEIVED = "POST_HEART_RECEIVED",
  POST_GOLDEN_HEART_RECEIVED = "POST_GOLDEN_HEART_RECEIVED",
  COMMENT_LOCK = "COMMENT_LOCK",
  REPLY_REMOVAL = "REPLY_REMOVAL",
  QUESTION_MARKED_GREAT = "QUESTION_MARKED_GREAT",
  BEST_COMMENT_FLAIR = "BEST_COMMENT_FLAIR",
  LOCK_POST = "LOCK_POST",
  NO_LOGIN = "NO_LOGIN",
  ACTIVATE_CUSTOM_PROFILE = "ACTIVATE_CUSTOM_PROFILE",
  ACTIVATE_LIKES = "ACTIVATE_LIKES",
  ACTIVATE_SUPER_LIKES = "ACTIVATE_SUPER_LIKES",
  ACTIVATE_USERNAME_COLORS = "ACTIVATE_USERNAME_COLORS",
  ACTIVATE_GIFT_100 = "ACTIVATE_GIFT_100",
  ACTIVATE_GIFT_300 = "ACTIVATE_GIFT_300",
  ACTIVATE_GIFT_500 = "ACTIVATE_GIFT_500",
  ACTIVATE_ADVERTISEMENT = "ACTIVATE_ADVERTISEMENT",
  GIFT_100 = "GIFT_100",
  GIFT_500 = "GIFT_500",
}

export const ACTION_POINTS: Record<UserAction, number> = {
  [UserAction.SIGNUP]: 10,
  [UserAction.LOGIN_PER_DAY]: 5,
  [UserAction.BIRTHDAY]: 30,
  [UserAction.ASK_QUESTION]: 5,
  [UserAction.ASK_POLL]: 5,
  [UserAction.QUESTION_ASKER_LIKE]: 5,
  [UserAction.POLL_ASKER_LIKE]: 5,
  [UserAction.QUESTION_ASKER_LIKE_10]: 10,
  [UserAction.QUESTION_ASKER_LIKE_50]: 50,
  [UserAction.POLL_ASKER_LIKE_HIGH]: 10,
  [UserAction.COMMENT_ON_POST]: 3,
  [UserAction.COMMENT_LIKED_10]: 10,
  [UserAction.COMMENT_LIKED_50]: 50,
  [UserAction.DELETE_QUESTION]: -15,
  [UserAction.DELETE_POLL]: -15,
  [UserAction.UPDATE_QUESTION]: -5,
  [UserAction.DELETE_COMMENT]: -50,
  [UserAction.DELETE_REPLY]: -50,
  [UserAction.SEND_PRIVATE_MESSAGE]: 3,
  [UserAction.SPECIAL_DAY_LOGIN]: 20,
  [UserAction.VOTE_ON_POLL]: 3,
  [UserAction.POST_HEART_RECEIVED]: 10,
  [UserAction.POST_GOLDEN_HEART_RECEIVED]: 20,
  [UserAction.COMMENT_LOCK]: -25,
  [UserAction.REPLY_REMOVAL]: -50,
  [UserAction.QUESTION_MARKED_GREAT]: 25,
  [UserAction.BEST_COMMENT_FLAIR]: 25,
  [UserAction.LOCK_POST]: -100,
  [UserAction.NO_LOGIN]: -2,
  [UserAction.ACTIVATE_CUSTOM_PROFILE]: -500,
  [UserAction.ACTIVATE_LIKES]: -100,
  [UserAction.ACTIVATE_SUPER_LIKES]: -150,
  [UserAction.ACTIVATE_USERNAME_COLORS]: -50,
  [UserAction.ACTIVATE_GIFT_100]: -100,
  [UserAction.ACTIVATE_GIFT_300]: -300,
  [UserAction.ACTIVATE_GIFT_500]: -500,
  [UserAction.ACTIVATE_ADVERTISEMENT]: -800,
  [UserAction.GIFT_100]: 100,
  [UserAction.GIFT_500]: 500,
};

export const ACTION_DISPLAY_NAMES: Record<UserAction, string> = {
  [UserAction.SIGNUP]: "Signed up",
  [UserAction.LOGIN_PER_DAY]: "Daily login",
  [UserAction.BIRTHDAY]: "Birthday bonus",
  [UserAction.ASK_QUESTION]: "Asked a question",
  [UserAction.ASK_POLL]: "Created a poll",
  [UserAction.QUESTION_ASKER_LIKE]: "Question liked",
  [UserAction.POLL_ASKER_LIKE]: "Poll liked",
  [UserAction.QUESTION_ASKER_LIKE_10]: "Question liked by 10 users",
  [UserAction.QUESTION_ASKER_LIKE_50]: "Question liked by 50 users",
  [UserAction.POLL_ASKER_LIKE_HIGH]: "Poll highly liked",
  [UserAction.COMMENT_ON_POST]: "Commented on a post",
  [UserAction.COMMENT_LIKED_10]: "Comment liked by 10 users",
  [UserAction.COMMENT_LIKED_50]: "Comment liked by 50 users",
  [UserAction.DELETE_QUESTION]: "Deleted a question",
  [UserAction.DELETE_POLL]: "Deleted a poll",
  [UserAction.UPDATE_QUESTION]: "Updated a question",
  [UserAction.DELETE_COMMENT]: "Deleted a comment",
  [UserAction.DELETE_REPLY]: "Deleted a reply",
  [UserAction.SEND_PRIVATE_MESSAGE]: "Sent a private message",
  [UserAction.SPECIAL_DAY_LOGIN]: "Special day login",
  [UserAction.VOTE_ON_POLL]: "Voted on a poll",
  [UserAction.POST_HEART_RECEIVED]: "Received a heart on post",
  [UserAction.POST_GOLDEN_HEART_RECEIVED]: "Received a golden heart on post",
  [UserAction.COMMENT_LOCK]: "Comment locked",
  [UserAction.REPLY_REMOVAL]: "Reply removed",
  [UserAction.QUESTION_MARKED_GREAT]: "Question marked as great",
  [UserAction.BEST_COMMENT_FLAIR]: "Received best comment flair",
  [UserAction.LOCK_POST]: "Post locked",
  [UserAction.NO_LOGIN]: "No login penalty",
  [UserAction.ACTIVATE_CUSTOM_PROFILE]: "Activated Custom Profile Features",
  [UserAction.ACTIVATE_LIKES]: "Activated Likes for Posts",
  [UserAction.ACTIVATE_SUPER_LIKES]: "Activated Super-Likes for Posts",
  [UserAction.ACTIVATE_USERNAME_COLORS]: "Activated Exclusive Username Colors",
  [UserAction.ACTIVATE_GIFT_100]: "Gifted 100 QP",
  [UserAction.ACTIVATE_GIFT_300]: "Gifted 300 QP",
  [UserAction.ACTIVATE_GIFT_500]: "Gifted 500 QP",
  [UserAction.ACTIVATE_ADVERTISEMENT]: "Activated Business Advertisement",
  [UserAction.GIFT_100]: "Gifted 100 QP",
  [UserAction.GIFT_500]: "Gifted 500 QP",
};
