export const relationshipStatusOptions = [
  "Single",
  "In a relationship",
  "Engaged",
  "Married",
  "It's complicated",
];

export const occupationOptions = [
  "Student",
  "Teacher / Educator",
  "Engineer",
  "Doctor / Healthcare Worker",
  "Nurse",
  "Psychologist / Therapist",
  "Artist / Designer",
  "Writer / Journalist",
  "IT Specialist / Developer",
  "Marketing / Advertising Specialist",
  "Salesperson / Consultant",
  "Entrepreneur / Business Owner",
  "Administrative Worker",
  "Lawyer / Legal Professional",
  "Finance / Banking Professional",
  "Scientist / Researcher",
  "Architect",
  "Manual Worker / Technician",
  "Retail / Customer Service Worker",
  "Hospitality / Tourism Worker",
  "Chef / Food Service Worker",
  "Fitness Trainer / Coach",
  "Musician / Performer",
  "Photographer / Videographer",
  "Government / Public Service Worker",
  "Human Resources Specialist",
  "Veterinarian / Animal Care Worker",
  "Real Estate Agent",
  "Social Worker / Non-profit Worker",
  "Unemployed / Looking for Opportunities",
  "Other",
];

export const educationLevelOptions = [
  "Student",
  "High school",
  "College",
  "Bachelor’s degree",
  "Master’s degree",
  "Doctorate",
  "Other",
];